name: Test Octoherd

on: push

jobs:
  test-octokit:
    runs-on: ubuntu-latest
    steps:
      - name: USE NODE JS
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"   
      - name: Check octoherd
        run: |
          npx @octoherd/script-hello-world --octoherd-token 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 "TFA5KOR/*" -R TFA5KOR/test-repo