name: Test Octoherd

on: push

jobs:
  test-octokit:
    runs-on: ubuntu-latest
    steps:
      - name: USE NODE JS
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"   
      - name: Check octoherd
        env:
          step_token: token ${{secrets.GITHUB_TOKEN}}
        run: |
          echo "${step_token}"
          npx @octoherd/script-hello-world --octoherd-token ${step_token} "TFA5KOR/*" -R TFA5KOR/test-repo